-------------------------------------
------- Created by T1GER#9080 -------
------------------------------------- 

Lang = {
  -- Menu Text:
  ['button_yes']         	    = 'Yes',
  ['button_no']         	    = 'No',
  ['button_return']         	= 'Return',
  ['rename_company']          = 'Rename Company',
  ['sell_company']            = 'Sell Company',
  ['company_level']           = 'Company Level',
  ['company_level_value']     = 'Company Level: %s',
  ['certificate_state']       = 'Has Certifcate: %s',
  ['buy_certificate']         = 'Buy Certifcate',
  ['request_job']             = 'Request Job',
  ['select_job_value']        = 'Select Job Value',
  ['select_job_vehicle']      = 'Select Job Vehicle',

  -- Draw 3D Texts:
  ['manage_company']          = '~r~[E]~s~ Manage Company',
  ['no_access_company']       = 'No Access',
  ['press_to_buy_firm']       = '~r~[E]~s~ Buy Company',
  ['only_one_company']        = 'ONLY OWN 1 COMPANY',
  ['load_the_job_veh']        = '~r~[E]~s~ FILL UP VEHICLE',
  ['pick_up_parcel']          = '~r~[E]~w~ Pick Up Parcel',
  ['put_parcel_in_veh']       = '~r~[E]~s~ Put Parcel in Vehicle',
  ['take_parcel_from_veh']    = '~r~[E]~s~ Take Parcel from Vehicle',
  ['deliver_parcel']          = '~r~[G]~s~ Deliver Parcel',
  ['return_vehicle']          = '~r~[E]~s~ Return Vehicle | Get Paycheck',
  ['fill_up_trailer']         = '~r~[E]~s~ FILL UP TRAILER',
  ['put_pallet_in_trailer']   = '~r~[E]~s~ Put Pallet in Trailer',
  ['park_the_forklift']       = '~r~[G]~s~ Park Forklift',
  ['take_the_forklift']       = '~r~[G]~s~ Take Out Forklift',
  ['deliver_pallet']          = '~r~[E]~s~ Deliver Pallet',

  -- Draw Mission Texts:
  ['pick_up_pallet']          = 'Pick up a ~r~Pallet~s~',
  ['load_into_trailer']       = 'Load the ~r~Pallet~s~ into the ~b~Trailer~s~',
  ['get_pallet_from_trailer'] = 'Getthe ~r~Pallet~s~ from the ~b~Trailer~s~',
  ['forklift_into_trailer']   = 'Drive the ~y~forklift~s~ into the ~b~Trailer~s~',
  ['pick_up_the_pallet']      = 'Pick up the ~r~Pallet~s~',
  ['park_instrunctions']      = 'Park the ~y~rear end~s~ of the ~b~Trailer~s~ at the ~r~Marker~s~',
  ['drop_off_the_pallet']     = 'Deliver the Pallet',

  -- Notifications:
  ['not_enough_money']        = 'You do not have enough money.',
  ['company_bought']          = 'You purchased a ~b~company~s~ and paid ~g~$%s~s~',
  ['company_sold']            = 'You sold your ~b~company~s~ and received ~g~$%s~s~',
  ['not_your_company']        = 'You do not own this company',
  ['company_renamed']         = 'You renamed your company to: ~b~%s~s~',
  ['alrdy_has_certificate']   = 'Your company already has the certificate',
  ['certificate_acquired']    = 'Your company has now acquired a certificate',
  ['job_level_mismatch']      = 'Your current level does not match the job requirements',
  ['job_needs_certificate']   = 'The job requires a certificate',
  ['deposit_veh_paid']        = 'You paid ~g~$%s~s~ in deposit for the vehicle.',
  ['not_enough_to_deposit']   = 'You do not have enough money to pay the deposit.',
  ['job_veh_spawned']         = 'Your vehicle has arrived and you received a pair of keys.',
  ['sit_in_job_veh']          = 'Please bring your job vehicle!',
  ['job_veh_mismatch']        = 'This is not your job vehicle?',
  ['vehicle_filled_up']       = 'You filled up the ~b~vehicle~s~. Get in and start the ~y~deliveries~s~.',
  ['parcel_not_ind_hand']     = 'Take a ~y~parcel~s~ from the vehicle.',
  ['set_delivery_route']      = 'Continue the ~b~delivery~s~ to the next ~y~destination~s~.',
  ['delivery_complete']       = 'You delivered all parcels. Return the ~b~vehicle~s~ and retrieve the ~g~paycheck~s~.',
  ['parcel_damaged_transit']  = 'This parcel was damaged in transit, no payment for this delivery',
  ['paycheck_add_amount']     = '~g~+$%s~s~ [added to paycheck]',
  ['deposit_not_returned']    = 'Deposit ~r~not returned~s~, vehicle is ~r~damaged~s~ too much.',
  ['deposit_returned']        = '~g~+$%s~s~ [vehicle deposit returned]',
  ['paycheck_received']       = '~g~+$%s~s~ [paycheck received]',
  ['delivery_pallets_done']   = 'You delivered all pallets. Return to the office retrieve the ~g~paycheck~s~.',
  ['pallet_damaged_transit']  = 'This pallet was damaged in transit, no payment for this delivery',
  ['not_inside_forklift']     = 'You need to bring the forklift',
  ['forklift_mismatch']       = 'This is not the correct forklift?',
  ['trailer_filled_up']       = 'You filled up the ~b~trailer~s~. Attach the trailer to truck and start the ~y~deliveries~s~.',
  ['park_fork_in_trailer']    = 'Park the ~y~forklift~s~ inside the ~b~trailer~s~ again.',
  ['place_pallet_on_ground']  = 'Park the ~r~pallet~s~ on the ground!',
  ['no_available_orders']     = 'No available orders to claim.',
  ['one_shop_allowed']        = 'You can only deliver to 1 shop at a time.',
  ['max_orders_selected']     = 'You have selected the max amount of orders to deliver at a time.',
  ['order_selected']          = 'Order selected.',

  -- Progress Bar Texts:
  ['delivering_load']         = 'DELIVERING LOAD',

  -- Blip Texts:
  ['vacant_companies']        = 'Vacant Companies',
  ['delivery_blip']           = 'Delivery Destination',
  ['trucking_blip']           = 'Delivery Drop-Off',
  ['return_blip']             = 'Get Paycheck',
}
